# -*- coding: utf-8 -*-
{
    'name': 'Hudson Indian Payroll',
    'version': '19.0.1.0.0',
    'category': 'Human Resources/Payroll',
    'summary': 'Indian Statutory Payroll Localization for Hudson HRMS',
    'author': 'Hudson Software Solutions',
    'depends': [
        'hr',
        'hr_payroll_community',
        'ohrms_payroll_reports',
    ],
    'data': [
        'security/ir.model.access.csv',
        'security/hds_in_bonus_security.xml',
        'security/hds_in_statutory_report_security.xml',
        'data/hr_salary_rule_category.xml',
        'data/hr_rule_parameters.xml',
        'data/hr_salary_rule_pf.xml',
        'data/hr_salary_rule_esic.xml',
        'data/hr_salary_rule_lwf.xml',
        'data/hr_salary_rule_gratuity.xml',
        'data/hr_salary_rule_professional_tax.xml',
        'data/lwf_state_rate_data.xml',
        'data/pt_state_slab_data.xml',
        'data/pt_period_schedule_data.xml',
        'data/hr_salary_rules.xml',
        'data/hr_bonus_payroll_data.xml',
        'data/hds_pt_report_tiles.xml',
        'views/hds_in_statutory_report_views.xml',
        'views/hds_pt_report_wizard_views.xml',
        'views/hds_pt_report_tile_views.xml',
        'views/payroll_menu_views.xml',
        'views/res_config_settings_views.xml',
        'views/hr_rule_parameter_views.xml',
        'views/lwf_state_rate_views.xml',
        'views/pt_state_slab_views.xml',
        'views/pt_period_schedule_views.xml',
        'views/hr_employee_views.xml',
        'views/hr_salary_rule_views.xml',
        'views/hr_contract_views.xml',
        'views/hr_payslip_views.xml',
        'views/hds_in_payroll_audit_views.xml',
        'wizard/hds_in_salary_revision_wizard_views.xml',
        'views/hds_in_salary_revision_views.xml',
        'views/hds_in_bonus_views.xml',
        'wizard/hds_in_bonus_import_wizard_views.xml',
    ],
    'installable': True,
    'application': False,
    'license': 'LGPL-3',
}
